module.exports = [
  "Pivot!",
  "We were on a break!",
  "See? He’s her lobster.",
  "I wish I could, but I don’t want to.",
  "This is all a moo point.",
  "How you doin'?",
  "Oh. My. God.",
  "I don’t even have a ‘pla.’",
  "They don’t know that we know they know we know.",
  "Come on, Ross, you’re a paleontologist. Dig a little deeper.",
  "You can’t just give up. Is that what a dinosaur would do?",
  "Could I be wearing any more clothes?",
  "Welcome to the real world. It sucks. You're gonna love it.",
  "Oh, Pheebs is short for Phoebe I thought that's just what we called each other.",
  "Joey doesn’t share food!",
  "You don’t own a TV? What’s all your furniture pointed at?",
  "I’m not great at the advice. Can I interest you in a sarcastic comment?",
  "So it seems like this Internet thing's here to stay.",
  "I say more dumb things before 9 a.m. than most people say all day.",
  "I KNOW!",
  "I'm a gym member. I try to go four times a week, but I've missed the last twelve hundred times.",
  "Can open. Worms everywhere!",
  "I’m glad we’re having a rehearsal dinner, I rarely practice my meals before I eat.",
  "Smelly cat, smelly cat, what are they feeding you?",
  "I’m gonna go get one of those job things.",
  "Over the line? You’re so far past the line that you can’t even see the line! The line is a dot to you!",
  "My sandwich? MY SANDWICH?!!",
];
